<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()>
Partial Class FormUsers
    Inherits System.Windows.Forms.Form

    'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()>
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.  
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()>
    Private Sub InitializeComponent()
        Me.Label1 = New System.Windows.Forms.Label()
        Me.txtId = New System.Windows.Forms.TextBox()
        Me.GroupBoxList = New System.Windows.Forms.GroupBox()
        Me.Panel2 = New System.Windows.Forms.Panel()
        Me.DataGridViewUser = New System.Windows.Forms.DataGridView()
        Me.Id = New System.Windows.Forms.DataGridViewTextBoxColumn()
        Me.DisplayName = New System.Windows.Forms.DataGridViewTextBoxColumn()
        Me.Username = New System.Windows.Forms.DataGridViewTextBoxColumn()
        Me.Password = New System.Windows.Forms.DataGridViewTextBoxColumn()
        Me.Position = New System.Windows.Forms.DataGridViewTextBoxColumn()
        Me.UserAccess = New System.Windows.Forms.DataGridViewTextBoxColumn()
        Me.CreatedOn = New System.Windows.Forms.DataGridViewTextBoxColumn()
        Me.CreatedBy = New System.Windows.Forms.DataGridViewTextBoxColumn()
        Me.RecordStatus = New System.Windows.Forms.DataGridViewTextBoxColumn()
        Me.Panel1 = New System.Windows.Forms.Panel()
        Me.btnSearchClear = New FontAwesome.Sharp.IconButton()
        Me.txtSearchBox = New System.Windows.Forms.TextBox()
        Me.grbForm = New System.Windows.Forms.GroupBox()
        Me.Label8 = New System.Windows.Forms.Label()
        Me.cbxRecordStatus = New System.Windows.Forms.ComboBox()
        Me.txtPosition = New System.Windows.Forms.TextBox()
        Me.Label7 = New System.Windows.Forms.Label()
        Me.Label6 = New System.Windows.Forms.Label()
        Me.cbxUserAccess = New System.Windows.Forms.ComboBox()
        Me.btnClear = New FontAwesome.Sharp.IconButton()
        Me.btnUpdate = New FontAwesome.Sharp.IconButton()
        Me.btnDelete = New FontAwesome.Sharp.IconButton()
        Me.txtRePassword = New System.Windows.Forms.TextBox()
        Me.Label5 = New System.Windows.Forms.Label()
        Me.txtPassword = New System.Windows.Forms.TextBox()
        Me.Label4 = New System.Windows.Forms.Label()
        Me.txtDisplayName = New System.Windows.Forms.TextBox()
        Me.Label3 = New System.Windows.Forms.Label()
        Me.btnSave = New FontAwesome.Sharp.IconButton()
        Me.txtUsername = New System.Windows.Forms.TextBox()
        Me.Label2 = New System.Windows.Forms.Label()
        Me.GroupBoxList.SuspendLayout()
        Me.Panel2.SuspendLayout()
        CType(Me.DataGridViewUser, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.Panel1.SuspendLayout()
        Me.grbForm.SuspendLayout()
        Me.SuspendLayout()
        '
        'Label1
        '
        Me.Label1.AutoSize = True
        Me.Label1.ForeColor = System.Drawing.Color.Gainsboro
        Me.Label1.Location = New System.Drawing.Point(25, 37)
        Me.Label1.Name = "Label1"
        Me.Label1.Size = New System.Drawing.Size(22, 20)
        Me.Label1.TabIndex = 0
        Me.Label1.Text = "Id"
        '
        'txtId
        '
        Me.txtId.BackColor = System.Drawing.Color.FromArgb(CType(CType(37, Byte), Integer), CType(CType(36, Byte), Integer), CType(CType(81, Byte), Integer))
        Me.txtId.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle
        Me.txtId.Enabled = False
        Me.txtId.Location = New System.Drawing.Point(133, 35)
        Me.txtId.Name = "txtId"
        Me.txtId.PlaceholderText = "Autogenerated"
        Me.txtId.ReadOnly = True
        Me.txtId.Size = New System.Drawing.Size(392, 27)
        Me.txtId.TabIndex = 1
        Me.txtId.Tag = ""
        '
        'GroupBoxList
        '
        Me.GroupBoxList.Anchor = CType((((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Bottom) _
            Or System.Windows.Forms.AnchorStyles.Left) _
            Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        Me.GroupBoxList.Controls.Add(Me.Panel2)
        Me.GroupBoxList.Controls.Add(Me.Panel1)
        Me.GroupBoxList.Location = New System.Drawing.Point(12, 334)
        Me.GroupBoxList.Name = "GroupBoxList"
        Me.GroupBoxList.Size = New System.Drawing.Size(1090, 385)
        Me.GroupBoxList.TabIndex = 2
        Me.GroupBoxList.TabStop = False
        Me.GroupBoxList.Text = "List"
        '
        'Panel2
        '
        Me.Panel2.Controls.Add(Me.DataGridViewUser)
        Me.Panel2.Dock = System.Windows.Forms.DockStyle.Fill
        Me.Panel2.Location = New System.Drawing.Point(3, 67)
        Me.Panel2.Name = "Panel2"
        Me.Panel2.Size = New System.Drawing.Size(1084, 315)
        Me.Panel2.TabIndex = 20
        '
        'DataGridViewUser
        '
        Me.DataGridViewUser.AllowUserToAddRows = False
        Me.DataGridViewUser.AllowUserToDeleteRows = False
        Me.DataGridViewUser.AllowUserToOrderColumns = True
        Me.DataGridViewUser.BackgroundColor = System.Drawing.Color.FromArgb(CType(CType(37, Byte), Integer), CType(CType(36, Byte), Integer), CType(CType(81, Byte), Integer))
        Me.DataGridViewUser.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize
        Me.DataGridViewUser.Columns.AddRange(New System.Windows.Forms.DataGridViewColumn() {Me.Id, Me.DisplayName, Me.Username, Me.Password, Me.Position, Me.UserAccess, Me.CreatedOn, Me.CreatedBy, Me.RecordStatus})
        Me.DataGridViewUser.Dock = System.Windows.Forms.DockStyle.Fill
        Me.DataGridViewUser.Location = New System.Drawing.Point(0, 0)
        Me.DataGridViewUser.MultiSelect = False
        Me.DataGridViewUser.Name = "DataGridViewUser"
        Me.DataGridViewUser.ReadOnly = True
        Me.DataGridViewUser.RowHeadersWidth = 51
        Me.DataGridViewUser.RowTemplate.Height = 29
        Me.DataGridViewUser.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect
        Me.DataGridViewUser.Size = New System.Drawing.Size(1084, 315)
        Me.DataGridViewUser.TabIndex = 0
        '
        'Id
        '
        Me.Id.DataPropertyName = "Id"
        Me.Id.HeaderText = "Id"
        Me.Id.MinimumWidth = 6
        Me.Id.Name = "Id"
        Me.Id.ReadOnly = True
        Me.Id.Width = 125
        '
        'DisplayName
        '
        Me.DisplayName.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill
        Me.DisplayName.DataPropertyName = "DisplayName"
        Me.DisplayName.HeaderText = "Display Name"
        Me.DisplayName.MinimumWidth = 6
        Me.DisplayName.Name = "DisplayName"
        Me.DisplayName.ReadOnly = True
        '
        'Username
        '
        Me.Username.DataPropertyName = "Username"
        Me.Username.HeaderText = "Username"
        Me.Username.MinimumWidth = 6
        Me.Username.Name = "Username"
        Me.Username.ReadOnly = True
        Me.Username.Width = 125
        '
        'Password
        '
        Me.Password.DataPropertyName = "Password"
        Me.Password.HeaderText = "Password"
        Me.Password.MinimumWidth = 6
        Me.Password.Name = "Password"
        Me.Password.ReadOnly = True
        Me.Password.Visible = False
        Me.Password.Width = 125
        '
        'Position
        '
        Me.Position.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill
        Me.Position.DataPropertyName = "Position"
        Me.Position.HeaderText = "Position"
        Me.Position.MinimumWidth = 6
        Me.Position.Name = "Position"
        Me.Position.ReadOnly = True
        '
        'UserAccess
        '
        Me.UserAccess.DataPropertyName = "UserAccess"
        Me.UserAccess.HeaderText = "User Access"
        Me.UserAccess.MinimumWidth = 6
        Me.UserAccess.Name = "UserAccess"
        Me.UserAccess.ReadOnly = True
        Me.UserAccess.Width = 125
        '
        'CreatedOn
        '
        Me.CreatedOn.DataPropertyName = "CreatedOn"
        Me.CreatedOn.HeaderText = "Created On"
        Me.CreatedOn.MinimumWidth = 6
        Me.CreatedOn.Name = "CreatedOn"
        Me.CreatedOn.ReadOnly = True
        Me.CreatedOn.Width = 125
        '
        'CreatedBy
        '
        Me.CreatedBy.DataPropertyName = "CreatedBy"
        Me.CreatedBy.HeaderText = "Created By"
        Me.CreatedBy.MinimumWidth = 6
        Me.CreatedBy.Name = "CreatedBy"
        Me.CreatedBy.ReadOnly = True
        Me.CreatedBy.Width = 125
        '
        'RecordStatus
        '
        Me.RecordStatus.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill
        Me.RecordStatus.DataPropertyName = "RecordStatus"
        Me.RecordStatus.HeaderText = "Record Status"
        Me.RecordStatus.MinimumWidth = 6
        Me.RecordStatus.Name = "RecordStatus"
        Me.RecordStatus.ReadOnly = True
        '
        'Panel1
        '
        Me.Panel1.Controls.Add(Me.btnSearchClear)
        Me.Panel1.Controls.Add(Me.txtSearchBox)
        Me.Panel1.Dock = System.Windows.Forms.DockStyle.Top
        Me.Panel1.Location = New System.Drawing.Point(3, 23)
        Me.Panel1.Name = "Panel1"
        Me.Panel1.Size = New System.Drawing.Size(1084, 44)
        Me.Panel1.TabIndex = 19
        '
        'btnSearchClear
        '
        Me.btnSearchClear.Cursor = System.Windows.Forms.Cursors.Hand
        Me.btnSearchClear.FlatStyle = System.Windows.Forms.FlatStyle.Flat
        Me.btnSearchClear.IconChar = FontAwesome.Sharp.IconChar.Eraser
        Me.btnSearchClear.IconColor = System.Drawing.Color.Black
        Me.btnSearchClear.IconFont = FontAwesome.Sharp.IconFont.[Auto]
        Me.btnSearchClear.IconSize = 23
        Me.btnSearchClear.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft
        Me.btnSearchClear.Location = New System.Drawing.Point(417, 7)
        Me.btnSearchClear.Name = "btnSearchClear"
        Me.btnSearchClear.Size = New System.Drawing.Size(80, 27)
        Me.btnSearchClear.TabIndex = 19
        Me.btnSearchClear.Text = "Clear"
        Me.btnSearchClear.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        Me.btnSearchClear.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText
        Me.btnSearchClear.UseVisualStyleBackColor = True
        '
        'txtSearchBox
        '
        Me.txtSearchBox.BackColor = System.Drawing.Color.FromArgb(CType(CType(37, Byte), Integer), CType(CType(36, Byte), Integer), CType(CType(81, Byte), Integer))
        Me.txtSearchBox.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle
        Me.txtSearchBox.Location = New System.Drawing.Point(19, 7)
        Me.txtSearchBox.Name = "txtSearchBox"
        Me.txtSearchBox.PlaceholderText = "Type To Search"
        Me.txtSearchBox.Size = New System.Drawing.Size(392, 27)
        Me.txtSearchBox.TabIndex = 18
        Me.txtSearchBox.Tag = "fdsf"
        '
        'grbForm
        '
        Me.grbForm.Anchor = CType(((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Left) _
            Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        Me.grbForm.Controls.Add(Me.Label8)
        Me.grbForm.Controls.Add(Me.cbxRecordStatus)
        Me.grbForm.Controls.Add(Me.txtPosition)
        Me.grbForm.Controls.Add(Me.Label7)
        Me.grbForm.Controls.Add(Me.Label6)
        Me.grbForm.Controls.Add(Me.cbxUserAccess)
        Me.grbForm.Controls.Add(Me.btnClear)
        Me.grbForm.Controls.Add(Me.btnUpdate)
        Me.grbForm.Controls.Add(Me.btnDelete)
        Me.grbForm.Controls.Add(Me.txtRePassword)
        Me.grbForm.Controls.Add(Me.Label5)
        Me.grbForm.Controls.Add(Me.txtPassword)
        Me.grbForm.Controls.Add(Me.Label4)
        Me.grbForm.Controls.Add(Me.txtDisplayName)
        Me.grbForm.Controls.Add(Me.Label3)
        Me.grbForm.Controls.Add(Me.btnSave)
        Me.grbForm.Controls.Add(Me.txtUsername)
        Me.grbForm.Controls.Add(Me.Label2)
        Me.grbForm.Controls.Add(Me.txtId)
        Me.grbForm.Controls.Add(Me.Label1)
        Me.grbForm.Location = New System.Drawing.Point(12, 3)
        Me.grbForm.Name = "grbForm"
        Me.grbForm.Size = New System.Drawing.Size(1090, 325)
        Me.grbForm.TabIndex = 3
        Me.grbForm.TabStop = False
        Me.grbForm.Text = "Form"
        '
        'Label8
        '
        Me.Label8.AutoSize = True
        Me.Label8.ForeColor = System.Drawing.Color.Gainsboro
        Me.Label8.Location = New System.Drawing.Point(25, 219)
        Me.Label8.Name = "Label8"
        Me.Label8.Size = New System.Drawing.Size(100, 20)
        Me.Label8.TabIndex = 19
        Me.Label8.Text = "Record Status"
        '
        'cbxRecordStatus
        '
        Me.cbxRecordStatus.BackColor = System.Drawing.Color.FromArgb(CType(CType(37, Byte), Integer), CType(CType(36, Byte), Integer), CType(CType(81, Byte), Integer))
        Me.cbxRecordStatus.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList
        Me.cbxRecordStatus.FlatStyle = System.Windows.Forms.FlatStyle.Flat
        Me.cbxRecordStatus.FormattingEnabled = True
        Me.cbxRecordStatus.Items.AddRange(New Object() {"Active", "In Active"})
        Me.cbxRecordStatus.Location = New System.Drawing.Point(133, 219)
        Me.cbxRecordStatus.Name = "cbxRecordStatus"
        Me.cbxRecordStatus.Size = New System.Drawing.Size(392, 28)
        Me.cbxRecordStatus.TabIndex = 4
        '
        'txtPosition
        '
        Me.txtPosition.BackColor = System.Drawing.Color.FromArgb(CType(CType(37, Byte), Integer), CType(CType(36, Byte), Integer), CType(CType(81, Byte), Integer))
        Me.txtPosition.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle
        Me.txtPosition.Location = New System.Drawing.Point(133, 171)
        Me.txtPosition.Name = "txtPosition"
        Me.txtPosition.PlaceholderText = "Enter Position"
        Me.txtPosition.Size = New System.Drawing.Size(392, 27)
        Me.txtPosition.TabIndex = 3
        Me.txtPosition.Tag = "fdsf"
        '
        'Label7
        '
        Me.Label7.AutoSize = True
        Me.Label7.ForeColor = System.Drawing.Color.Gainsboro
        Me.Label7.Location = New System.Drawing.Point(25, 173)
        Me.Label7.Name = "Label7"
        Me.Label7.Size = New System.Drawing.Size(61, 20)
        Me.Label7.TabIndex = 16
        Me.Label7.Text = "Position"
        '
        'Label6
        '
        Me.Label6.AutoSize = True
        Me.Label6.ForeColor = System.Drawing.Color.Gainsboro
        Me.Label6.Location = New System.Drawing.Point(25, 125)
        Me.Label6.Name = "Label6"
        Me.Label6.Size = New System.Drawing.Size(86, 20)
        Me.Label6.TabIndex = 15
        Me.Label6.Text = "User Access"
        '
        'cbxUserAccess
        '
        Me.cbxUserAccess.BackColor = System.Drawing.Color.FromArgb(CType(CType(37, Byte), Integer), CType(CType(36, Byte), Integer), CType(CType(81, Byte), Integer))
        Me.cbxUserAccess.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList
        Me.cbxUserAccess.FlatStyle = System.Windows.Forms.FlatStyle.Flat
        Me.cbxUserAccess.FormattingEnabled = True
        Me.cbxUserAccess.Items.AddRange(New Object() {"Admin", "Standard"})
        Me.cbxUserAccess.Location = New System.Drawing.Point(133, 125)
        Me.cbxUserAccess.Name = "cbxUserAccess"
        Me.cbxUserAccess.Size = New System.Drawing.Size(392, 28)
        Me.cbxUserAccess.TabIndex = 2
        '
        'btnClear
        '
        Me.btnClear.Anchor = CType((System.Windows.Forms.AnchorStyles.Bottom Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        Me.btnClear.Cursor = System.Windows.Forms.Cursors.Hand
        Me.btnClear.FlatStyle = System.Windows.Forms.FlatStyle.Flat
        Me.btnClear.IconChar = FontAwesome.Sharp.IconChar.Eraser
        Me.btnClear.IconColor = System.Drawing.Color.Black
        Me.btnClear.IconFont = FontAwesome.Sharp.IconFont.[Auto]
        Me.btnClear.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft
        Me.btnClear.Location = New System.Drawing.Point(586, 260)
        Me.btnClear.Name = "btnClear"
        Me.btnClear.Size = New System.Drawing.Size(118, 49)
        Me.btnClear.TabIndex = 13
        Me.btnClear.Text = "Clear"
        Me.btnClear.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        Me.btnClear.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText
        Me.btnClear.UseVisualStyleBackColor = True
        '
        'btnUpdate
        '
        Me.btnUpdate.Anchor = CType((System.Windows.Forms.AnchorStyles.Bottom Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        Me.btnUpdate.Cursor = System.Windows.Forms.Cursors.Hand
        Me.btnUpdate.FlatStyle = System.Windows.Forms.FlatStyle.Flat
        Me.btnUpdate.IconChar = FontAwesome.Sharp.IconChar.Edit
        Me.btnUpdate.IconColor = System.Drawing.Color.Black
        Me.btnUpdate.IconFont = FontAwesome.Sharp.IconFont.[Auto]
        Me.btnUpdate.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft
        Me.btnUpdate.Location = New System.Drawing.Point(834, 260)
        Me.btnUpdate.Name = "btnUpdate"
        Me.btnUpdate.Size = New System.Drawing.Size(118, 49)
        Me.btnUpdate.TabIndex = 12
        Me.btnUpdate.Text = "Update"
        Me.btnUpdate.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        Me.btnUpdate.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText
        Me.btnUpdate.UseVisualStyleBackColor = True
        '
        'btnDelete
        '
        Me.btnDelete.Anchor = CType((System.Windows.Forms.AnchorStyles.Bottom Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        Me.btnDelete.Cursor = System.Windows.Forms.Cursors.Hand
        Me.btnDelete.FlatStyle = System.Windows.Forms.FlatStyle.Flat
        Me.btnDelete.IconChar = FontAwesome.Sharp.IconChar.TrashAlt
        Me.btnDelete.IconColor = System.Drawing.Color.Black
        Me.btnDelete.IconFont = FontAwesome.Sharp.IconFont.[Auto]
        Me.btnDelete.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft
        Me.btnDelete.Location = New System.Drawing.Point(958, 260)
        Me.btnDelete.Name = "btnDelete"
        Me.btnDelete.Size = New System.Drawing.Size(118, 49)
        Me.btnDelete.TabIndex = 11
        Me.btnDelete.Text = "Delete"
        Me.btnDelete.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        Me.btnDelete.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText
        Me.btnDelete.UseVisualStyleBackColor = True
        '
        'txtRePassword
        '
        Me.txtRePassword.BackColor = System.Drawing.Color.FromArgb(CType(CType(37, Byte), Integer), CType(CType(36, Byte), Integer), CType(CType(81, Byte), Integer))
        Me.txtRePassword.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle
        Me.txtRePassword.Location = New System.Drawing.Point(642, 126)
        Me.txtRePassword.Name = "txtRePassword"
        Me.txtRePassword.PlaceholderText = "Re-Enter Password"
        Me.txtRePassword.Size = New System.Drawing.Size(419, 27)
        Me.txtRePassword.TabIndex = 7
        Me.txtRePassword.Tag = "fdsf"
        Me.txtRePassword.UseSystemPasswordChar = True
        '
        'Label5
        '
        Me.Label5.AutoSize = True
        Me.Label5.ForeColor = System.Drawing.Color.Gainsboro
        Me.Label5.Location = New System.Drawing.Point(543, 128)
        Me.Label5.Name = "Label5"
        Me.Label5.Size = New System.Drawing.Size(93, 20)
        Me.Label5.TabIndex = 9
        Me.Label5.Text = "Re-Password"
        '
        'txtPassword
        '
        Me.txtPassword.BackColor = System.Drawing.Color.FromArgb(CType(CType(37, Byte), Integer), CType(CType(36, Byte), Integer), CType(CType(81, Byte), Integer))
        Me.txtPassword.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle
        Me.txtPassword.Location = New System.Drawing.Point(642, 81)
        Me.txtPassword.Name = "txtPassword"
        Me.txtPassword.PlaceholderText = "Enter Password"
        Me.txtPassword.Size = New System.Drawing.Size(419, 27)
        Me.txtPassword.TabIndex = 6
        Me.txtPassword.Tag = "fdsf"
        Me.txtPassword.UseSystemPasswordChar = True
        '
        'Label4
        '
        Me.Label4.AutoSize = True
        Me.Label4.ForeColor = System.Drawing.Color.Gainsboro
        Me.Label4.Location = New System.Drawing.Point(543, 83)
        Me.Label4.Name = "Label4"
        Me.Label4.Size = New System.Drawing.Size(70, 20)
        Me.Label4.TabIndex = 7
        Me.Label4.Text = "Password"
        '
        'txtDisplayName
        '
        Me.txtDisplayName.BackColor = System.Drawing.Color.FromArgb(CType(CType(37, Byte), Integer), CType(CType(36, Byte), Integer), CType(CType(81, Byte), Integer))
        Me.txtDisplayName.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle
        Me.txtDisplayName.Location = New System.Drawing.Point(133, 81)
        Me.txtDisplayName.Name = "txtDisplayName"
        Me.txtDisplayName.PlaceholderText = "Enter Display Name"
        Me.txtDisplayName.Size = New System.Drawing.Size(392, 27)
        Me.txtDisplayName.TabIndex = 1
        Me.txtDisplayName.Tag = "fdsf"
        '
        'Label3
        '
        Me.Label3.AutoSize = True
        Me.Label3.ForeColor = System.Drawing.Color.Gainsboro
        Me.Label3.Location = New System.Drawing.Point(25, 83)
        Me.Label3.Name = "Label3"
        Me.Label3.Size = New System.Drawing.Size(102, 20)
        Me.Label3.TabIndex = 5
        Me.Label3.Text = "Display Name"
        '
        'btnSave
        '
        Me.btnSave.Anchor = CType((System.Windows.Forms.AnchorStyles.Bottom Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        Me.btnSave.Cursor = System.Windows.Forms.Cursors.Hand
        Me.btnSave.FlatStyle = System.Windows.Forms.FlatStyle.Flat
        Me.btnSave.IconChar = FontAwesome.Sharp.IconChar.Save
        Me.btnSave.IconColor = System.Drawing.Color.Black
        Me.btnSave.IconFont = FontAwesome.Sharp.IconFont.[Auto]
        Me.btnSave.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft
        Me.btnSave.Location = New System.Drawing.Point(710, 260)
        Me.btnSave.Name = "btnSave"
        Me.btnSave.Size = New System.Drawing.Size(118, 49)
        Me.btnSave.TabIndex = 8
        Me.btnSave.Text = "Save"
        Me.btnSave.TextAlign = System.Drawing.ContentAlignment.MiddleLeft
        Me.btnSave.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText
        Me.btnSave.UseVisualStyleBackColor = True
        '
        'txtUsername
        '
        Me.txtUsername.BackColor = System.Drawing.Color.FromArgb(CType(CType(37, Byte), Integer), CType(CType(36, Byte), Integer), CType(CType(81, Byte), Integer))
        Me.txtUsername.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle
        Me.txtUsername.Location = New System.Drawing.Point(642, 35)
        Me.txtUsername.Name = "txtUsername"
        Me.txtUsername.PlaceholderText = "Enter Username"
        Me.txtUsername.Size = New System.Drawing.Size(419, 27)
        Me.txtUsername.TabIndex = 5
        Me.txtUsername.Tag = "fdsf"
        '
        'Label2
        '
        Me.Label2.AutoSize = True
        Me.Label2.ForeColor = System.Drawing.Color.Gainsboro
        Me.Label2.Location = New System.Drawing.Point(543, 37)
        Me.Label2.Name = "Label2"
        Me.Label2.Size = New System.Drawing.Size(75, 20)
        Me.Label2.TabIndex = 2
        Me.Label2.Text = "Username"
        '
        'FormUsers
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(8.0!, 20.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.BackColor = System.Drawing.Color.FromArgb(CType(CType(37, Byte), Integer), CType(CType(36, Byte), Integer), CType(CType(81, Byte), Integer))
        Me.ClientSize = New System.Drawing.Size(1114, 731)
        Me.Controls.Add(Me.grbForm)
        Me.Controls.Add(Me.GroupBoxList)
        Me.Name = "FormUsers"
        Me.Text = "Users"
        Me.GroupBoxList.ResumeLayout(False)
        Me.Panel2.ResumeLayout(False)
        CType(Me.DataGridViewUser, System.ComponentModel.ISupportInitialize).EndInit()
        Me.Panel1.ResumeLayout(False)
        Me.Panel1.PerformLayout()
        Me.grbForm.ResumeLayout(False)
        Me.grbForm.PerformLayout()
        Me.ResumeLayout(False)

    End Sub

    Friend WithEvents Label1 As Label
    Friend WithEvents txtId As TextBox
    Friend WithEvents GroupBoxList As GroupBox
    Friend WithEvents grbForm As GroupBox
    Friend WithEvents txtUsername As TextBox
    Friend WithEvents Label2 As Label
    Friend WithEvents btnSave As FontAwesome.Sharp.IconButton
    Friend WithEvents txtRePassword As TextBox
    Friend WithEvents Label5 As Label
    Friend WithEvents txtPassword As TextBox
    Friend WithEvents Label4 As Label
    Friend WithEvents txtDisplayName As TextBox
    Friend WithEvents Label3 As Label
    Friend WithEvents btnUpdate As FontAwesome.Sharp.IconButton
    Friend WithEvents btnDelete As FontAwesome.Sharp.IconButton
    Friend WithEvents btnClear As FontAwesome.Sharp.IconButton
    Friend WithEvents Label6 As Label
    Friend WithEvents cbxUserAccess As ComboBox
    Friend WithEvents txtPosition As TextBox
    Friend WithEvents Label7 As Label
    Friend WithEvents Panel2 As Panel
    Friend WithEvents DataGridViewUser As DataGridView
    Friend WithEvents Panel1 As Panel
    Friend WithEvents txtSearchBox As TextBox
    Friend WithEvents btnSearchClear As FontAwesome.Sharp.IconButton
    Friend WithEvents Label8 As Label
    Friend WithEvents cbxRecordStatus As ComboBox
    Friend WithEvents Id As DataGridViewTextBoxColumn
    Friend WithEvents DisplayName As DataGridViewTextBoxColumn
    Friend WithEvents Username As DataGridViewTextBoxColumn
    Friend WithEvents Password As DataGridViewTextBoxColumn
    Friend WithEvents Position As DataGridViewTextBoxColumn
    Friend WithEvents UserAccess As DataGridViewTextBoxColumn
    Friend WithEvents CreatedOn As DataGridViewTextBoxColumn
    Friend WithEvents CreatedBy As DataGridViewTextBoxColumn
    Friend WithEvents RecordStatus As DataGridViewTextBoxColumn
End Class
